vich_uploader:
    db_driver: orm

    mappings:
        produit_images:
            uri_prefix: '%produit_images%'
            upload_destination: '%kernel.project_dir%/public%produit_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
